#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Mini TV · UI local-refresh baseline"

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
PROBE_BASE_COMMIT="0e78f071d726444e37d623ec993e0bfae3a01935"
PROBE_PATCH="$SCRIPT_DIR/probe.patch"
SUMMARIZER="$SCRIPT_DIR/summarize.py"
CAPTURE="$SCRIPT_DIR/capture.py"
if [[ -n "${IDF_EXPORT:-}" ]]; then
  IDF_EXPORT="$IDF_EXPORT"
elif [[ -n "${IDF_PATH:-}" ]]; then
  IDF_EXPORT="$IDF_PATH/export.sh"
else
  IDF_EXPORT="$HOME/.espressif/v6.0.2/esp-idf/export.sh"
fi
SESSION_DIR="$(mktemp -d -t minitv-ui-perf.XXXXXX)"
PROBE_WORKTREE="$SESSION_DIR/worktree"
FLASH_BACKUP="$SESSION_DIR/original-flash-4mb.bin"
RESTORE_READBACK="$SESSION_DIR/restored-flash-4mb.bin"
RAW_LOG="$SESSION_DIR/serial.raw.log"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
ARTIFACT_DIR="$REPO_ROOT/Firmware/docs/acceptance/artifacts"
FILTERED_LOG="$ARTIFACT_DIR/ui-perf-baseline-$STAMP.log"
SUMMARY="$ARTIFACT_DIR/ui-perf-baseline-$STAMP.md"
FILTERED_TEMP="$SESSION_DIR/ui-perf-baseline-$STAMP.log"
SUMMARY_TEMP="$SESSION_DIR/ui-perf-baseline-$STAMP.md"
PORT=""
RESTORE_NEEDED=0
CAPTURE_OK=1
ARTIFACTS_PUBLISHED=0
FLASH_BACKUP_SHA256=""
RAW_LOG_SHA256=""
PROBE_PATCH_SHA256=""

restore_original_flash() {
  [[ -f "$FLASH_BACKUP" ]] || return 1
  [[ "$(stat -c '%s' "$FLASH_BACKUP")" -eq 4194304 ]] || {
    warn "flash backup is not exactly 4 MiB"
    return 1
  }
  python -m esptool --chip esp32c3 --port "$PORT" --after no-reset write-flash 0 "$FLASH_BACKUP" || return 1
  python -m esptool --chip esp32c3 --port "$PORT" --after no-reset read-flash 0 0x400000 "$RESTORE_READBACK" || return 1
  if ! cmp -s "$FLASH_BACKUP" "$RESTORE_READBACK"; then
    warn "restored flash does not match the original 4 MiB backup"
    return 1
  fi
  python -m esptool --chip esp32c3 --port "$PORT" run || return 1
  RESTORE_NEEDED=0
  rm -f "$RESTORE_READBACK"
  return 0
}

cleanup_session() {
  local status=$?
  trap - EXIT
  if [[ "$RESTORE_NEEDED" -eq 1 && -f "$FLASH_BACKUP" && -n "$PORT" ]]; then
    warn "wizard interrupted after probe flash; restoring and verifying the original flash"
    if restore_original_flash; then
      rm -f "$FLASH_BACKUP"
      say "Original 4 MiB flash restored and verified automatically."
    else
      warn "automatic restoration or verification failed; keep $SESSION_DIR"
      note "source '$IDF_EXPORT' and restore $FLASH_BACKUP before using the device"
    fi
  fi
  if [[ "$ARTIFACTS_PUBLISHED" -eq 0 ]]; then
    rm -f "$FILTERED_LOG" "$SUMMARY"
  fi
  if [[ "$RESTORE_NEEDED" -eq 0 && -d "$PROBE_WORKTREE" ]]; then
    git -C "$REPO_ROOT" worktree remove --force "$PROBE_WORKTREE" >/dev/null 2>&1 || true
  fi
  [[ "$status" -eq 0 && "$RESTORE_NEEDED" -eq 0 ]] && rm -rf "$SESSION_DIR"
  exit "$status"
}
trap cleanup_session EXIT


note "Temporary recovery files: $SESSION_DIR"
note "Raw serial output and the full flash backup stay outside the repository."

stage "Prepare isolated probe"
say "The probe is applied only in a detached temporary worktree."
step "Checking the pinned source, probe patch, Python summarizer, and ESP-IDF environment."
git -C "$REPO_ROOT" cat-file -e "$PROBE_BASE_COMMIT^{commit}"
[[ -f "$PROBE_PATCH" ]] || { warn "missing $PROBE_PATCH"; exit 1; }
[[ -x "$SUMMARIZER" ]] || { warn "summarizer is not executable: $SUMMARIZER"; exit 1; }
[[ -f "$IDF_EXPORT" ]] || { warn "ESP-IDF export script not found: $IDF_EXPORT"; exit 1; }
[[ -x "$CAPTURE" ]] || { warn "serial capture tool is not executable: $CAPTURE"; exit 1; }
git -C "$REPO_ROOT" worktree add --detach "$PROBE_WORKTREE" "$PROBE_BASE_COMMIT"
git -C "$PROBE_WORKTREE" apply --check "$PROBE_PATCH"
git -C "$PROBE_WORKTREE" apply "$PROBE_PATCH"
say "Probe worktree ready at $PROBE_WORKTREE"

stage "Build probe firmware"
say "This build keeps the verified 10 MHz SPI clock and 40-line DMA buffers."
# shellcheck disable=SC1090
source "$IDF_EXPORT"
(cd "$PROBE_WORKTREE/Firmware" && idf.py build)
say "Probe firmware built successfully."

stage "Connect Mini TV"
say "Connect the ESP32-C3 Mini TV with a data-capable USB cable."
while true; do
  mapfile -t PORTS < <(compgen -G '/dev/ttyACM*' || true; compgen -G '/dev/ttyUSB*' || true)
  if (( ${#PORTS[@]} == 1 )); then
    PORT="${PORTS[0]}"
    break
  fi
  if (( ${#PORTS[@]} > 1 )); then
    printf '  Detected ports: %s\n' "${PORTS[*]}"
    ask PORT "Enter the Mini TV serial port:"
    [[ -c "$PORT" ]] && break
    warn "not a character device: $PORT"
  else
    warn "no /dev/ttyACM* or /dev/ttyUSB* device detected"
    pause "Connect the board, then press Enter to scan again."
  fi
done
[[ -r "$PORT" && -w "$PORT" ]] || { warn "no read/write permission for $PORT"; exit 1; }
say "Using $PORT"

stage "Back up and flash"
warn "The next step temporarily replaces the firmware on $PORT."
say "A raw 4 MiB backup is stored only at $FLASH_BACKUP and restored in Stage 6."
confirm "Back up the exact current flash and install the temporary probe?" || exit 1
python -m esptool --chip esp32c3 --port "$PORT" read-flash 0 0x400000 "$FLASH_BACKUP"
[[ "$(stat -c '%s' "$FLASH_BACKUP")" -eq 4194304 ]] || {
  warn "backup size is not exactly 4 MiB"
  exit 1
}
FLASH_BACKUP_SHA256="$(sha256sum "$FLASH_BACKUP" | cut -d ' ' -f 1)"
PROBE_PATCH_SHA256="$(sha256sum "$PROBE_PATCH" | cut -d ' ' -f 1)"
RESTORE_NEEDED=1
(cd "$PROBE_WORKTREE/Firmware" && idf.py -p "$PORT" flash)
say "Temporary probe flashed. Saved recovery image: $FLASH_BACKUP"

stage "Capture all scenarios"
say "The run takes about two minutes: full-screen once, true static idle, representative clock/date/temperature text, 16×16 motion, then motion samples synchronized with Wi-Fi scans."
say "Network tasks remain enabled. Do not touch the display or disconnect USB."
set +e
"$CAPTURE" --port "$PORT" --output "$RAW_LOG" --timeout 165
CAPTURE_STATUS=$?
set -e
if [[ "$CAPTURE_STATUS" -ne 0 ]]; then
  warn "serial capture failed with status $CAPTURE_STATUS"
  CAPTURE_OK=0
fi
grep -E 'PERF-PROBE|baseline' "$RAW_LOG" | tr -d '\r' > "$FILTERED_TEMP" || true
if ! grep -q 'PERF-PROBE.*begin' "$FILTERED_TEMP"; then
  warn "probe begin marker missing"
  CAPTURE_OK=0
fi
if ! grep -q 'PERF-PROBE.*done scenarios=7' "$FILTERED_TEMP"; then
  warn "probe completion marker missing"
  CAPTURE_OK=0
fi
if [[ "$CAPTURE_OK" -eq 1 ]]; then
  "$SUMMARIZER" "$FILTERED_TEMP" --output "$SUMMARY_TEMP"
  RAW_LOG_SHA256="$(sha256sum "$RAW_LOG" | cut -d ' ' -f 1)"
else
  warn "capture is incomplete; raw recovery log remains at $RAW_LOG"
fi

stage "Restore exact original flash"
warn "Do not disconnect the device until restoration completes."
confirm "Restore and byte-verify the exact 4 MiB flash backup now?" || {
  warn "not restored; keep $FLASH_BACKUP and restore it before using the device"
  exit 1
}
restore_original_flash || {
  warn "restoration could not be byte-verified; keep $SESSION_DIR"
  exit 1
}
git -C "$REPO_ROOT" worktree remove --force "$PROBE_WORKTREE"
say "Original device flash restored and byte-verified; temporary worktree removed."
if [[ "$CAPTURE_OK" -ne 1 ]]; then
  warn "Measurement was incomplete. Raw serial evidence remains at $RAW_LOG"
  exit 1
fi
{
  printf '\n## Provenance and restoration receipt\n\n'
  printf -- '- Hardware: ESP32-C3 with 320×240 landscape ST7789; see `Firmware/docs/hardware/HADRWARE.md`.\n'
  printf -- '- Probe base commit: `%s`.\n' "$PROBE_BASE_COMMIT"
  printf -- '- Probe patch SHA-256: `%s`.\n' "$PROBE_PATCH_SHA256"
  printf -- '- ESP-IDF: `%s`; esptool: `%s`.\n' "$(idf.py --version)" "$(python -m esptool version | sed -n '1p')"
  printf -- '- Capture: one physical unit over native USB serial/JTAG; unit identifier redacted; UTC artifact stamp `%s`.\n' "$STAMP"
  printf -- '- Build identity: app version `0e78f07-dirty`, defined by the base commit and probe patch above.\n'
  printf -- '- Capture command: `capture.py --port <redacted> --output <temporary>/serial.raw.log --timeout 165`.\n'
  printf -- '- Raw serial log SHA-256: `%s`; raw log was retained only in the temporary session until validation.\n' "$RAW_LOG_SHA256"
  printf -- '- Original flash backup: 4,194,304 bytes, SHA-256 `%s`.\n' "$FLASH_BACKUP_SHA256"
  printf -- '- Restoration: all 4,194,304 bytes were read back and compared byte-for-byte with the backup before reset; result `MATCH`.\n'
} >> "$SUMMARY_TEMP"
mkdir -p "$ARTIFACT_DIR"
mv "$FILTERED_TEMP" "$FILTERED_LOG"
mv "$SUMMARY_TEMP" "$SUMMARY"
ARTIFACTS_PUBLISHED=1
rm -f "$FLASH_BACKUP"
rm -rf "$SESSION_DIR"
trap - EXIT
say "Keep the two redacted artifacts for issue evidence:"
note "$FILTERED_LOG"
note "$SUMMARY"

finish