#pragma once

#include "driver/gpio.h"

#define BOARD_LCD_SCLK_GPIO GPIO_NUM_4
#define BOARD_LCD_MOSI_GPIO GPIO_NUM_6
#define BOARD_LCD_DC_GPIO GPIO_NUM_7
#define BOARD_LCD_RST_GPIO GPIO_NUM_8
#define BOARD_LCD_CS_GPIO GPIO_NUM_10
#define BOARD_LCD_BLK_GPIO GPIO_NUM_5

#define BOARD_TOUCH_SDA_GPIO GPIO_NUM_2
#define BOARD_TOUCH_SCL_GPIO GPIO_NUM_3
#define BOARD_TOUCH_INT_GPIO GPIO_NUM_0
#define BOARD_TOUCH_RST_GPIO GPIO_NUM_1
#define BOARD_BOOT_GPIO GPIO_NUM_9

#define BOARD_LCD_H_RES 240
#define BOARD_LCD_V_RES 320
#define BOARD_LCD_DMA_LINES 40
#define BOARD_CONTROL_CENTER_HOTZONE_PX 45
